### ISSUE TITLE
Gem completely breaks with latest version of Faraday.

### ISSUE THREAD

**Issue by sealabcore** [GetStream/stream-chat-ruby#108]
This gems gemspec needs to specify a stricter version for Faraday because it completely breaks with the latest 2.X version.

```
no implicit conversion of nil into String
/Users/miketaylor/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `initialize'
/Users/miketaylor/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `new'
/Users/miketaylor/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/Users/miketaylor/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/stream-chat-ruby-3.0.0/lib/stream-chat/client.rb:973:in `parse_response'
/Users/miketaylor/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10148/lib/types/private/methods/call_validation.rb:161:in `bind_call'
```

<img width="335" alt="Screen Shot 2022-08-12 at 10 29 03 AM" src="https://user-images.githubusercontent.com/79464/184412119-9bf9961a-4c7f-4e0a-bf02-8da46d619ec0.png">

**Comment by ffenix113** [comment]
Thank you for opening the issue.

We will pin versions required for this gem so there would not be such issues in the future.

I will update this issue once necessary changes will be done.

**Comment by ffenix113** [comment]
We pushed new version of this gem with pinned dependencies versions so that this will not happen in the future.

Please see new version v3.1.0 here: https://rubygems.org/gems/stream-chat-ruby/versions/3.1.0
