### ISSUE TITLE
Improve release workflow

### ISSUE THREAD

**Issue by ffenix113** [GetStream/stream-chat-ruby#112]
- We currently don't include `chore` commits in changelog, but they are also useful to understand the changes.
- Also we should replace our release handling to [release-please](https://github.com/googleapis/release-please), as mentioned on the [page](https://www.npmjs.com/package/standard-version) of the package that we currently use to generate changelog.
- We now include `Gemfile.lock` in git, and it also must be updated when creating a release.

**Comment by ferhatelmas** [comment]
It's a good change, let's make it everywhere as much as possible.

**Comment by ferhatelmas** [comment]
1. added chore
2. it seems current setup would work for the foreseeable future
3. reverted it
so closing this, we can resonsider in the future if needed
