### ISSUE TITLE
Relax dependency versions

### ISSUE THREAD

**Issue by jpalumickas** [GetStream/stream-chat-ruby#113]
Hello,

In 3.1.0 all dependency versions was strictly set, but other gems using also these dependencies, so we cannot normally upgrade `stream-chat-ruby`. It's better to relax to minor version, like this `faraday` `~> 1.10` so other gems can be upgraded also

**Comment by ferhatelmas** [comment]
related to https://github.com/GetStream/stream-chat-ruby/issues/108

@ffenix113 could you chime in ?

**Comment by ffenix113** [comment]
We can do that as long as it will not break the library(for example like in https://github.com/GetStream/stream-chat-ruby/issues/108).

We will investigate having looser dependencies versions and release new version ASAP.

**Comment by sailor** [comment]
I have the same problem with the jwt gem which is now frozen at `2.3.0`.  There is already a lot of fixes that has been released: https://github.com/jwt/ruby-jwt/blob/v2.5.0/CHANGELOG.md

**Comment by jpalumickas** [comment]
@ffenix113 any news about this one? I can make a PR if you need a help.

**Comment by ffenix113** [comment]
Thank you for offering some help.

We plan to release a major version that will fix this issue, along with some other improvement(s) and dropping EOL Ruby versions some time in the future.

In the meantime - we would gladly accept MR for this as well, thanks @jpalumickas.
