### ISSUE TITLE
Error handling format does not match actual api format

### ISSUE THREAD

**Issue by betterwithranch** [GetStream/stream-chat-ruby#15]
`StreamChat::StreamAPIException` constructor parses incorrect response format.  The code is expecting a format like this

     {
       "data": {
          "code": 4,
          "message": "UpdateChannel failed ...",
       }
     }

but the actual response is

    {
       "code": 4,
       "message": "UpdateChannel failed ..."
    }

As a result, these values are set to the defaults of `unknown` in all exceptions and no details are provided for logging or exception notifications.

**Comment by bogdan-getstream** [comment]
Hi @betterwithranch, thank you for reporting, we are working on fixing that
