### ISSUE TITLE
Response headers are not available on successful requests

### ISSUE THREAD

**Issue by betterwithranch** [GetStream/stream-chat-ruby#18]
Currently, if an api request is succesful, the response body is parsed and returned, but the response headers are discarded.  But, if an exception is returned, the response object is returned, making the response headers available.

Since the current api rate limit status is included in the response headers, there is no way to proactively monitor the api rate limits prior to getting an exception.

Obviously, we couldn't change the return values without breaking every method's interface, but maybe we could store it in the client so it could be accessed by a separate method?

Something like this, maybe?

    client = StreamChat::Client.new('key', 'secret')
    client.query_channels({id: 'channelid'})
    client.rate_limits  # => { "query_channels": { limit: 10000, remaining: 9996, reset: 1587587580 })

**Comment by betterwithranch** [comment]
Alternatively, if we could just add a hook to `make_http_request` to allow for introspection of the response headers before parsing, that would allow me to customize a solution.

    client.on_response = Proc.new { |response| puts response }

**Comment by ffenix113** [comment]
Response headers and rate limit information was added in https://github.com/GetStream/stream-chat-ruby/pull/72 and released in v2.18.0.

Please take a look at it and open a new issue if something is missing or wrong.

Sorry that this took a while to be implemented.
