### ISSUE TITLE
Sorting messages using channel query method

### ISSUE THREAD

**Issue by hgeorgilas** [GetStream/stream-chat-ruby#29]
It seems that this is related to https://github.com/GetStream/stream-chat-python/issues/9
Your [API Docs](https://getstream.io/chat/docs_rest/#query-channels) is not documenting a way to sort channel messages, I'm referring to ` POST /channels/{type}/{id}/query` endpoint. 

Is there any way around this? 
Thanks

**Comment by peterdeme** [comment]
Look for the `sort` parameter in the [documentation](https://getstream.io/chat/docs/rest/#channels-querychannels). Plus examples [here](https://getstream.io/chat/docs/other-rest/query_channels/).

Thanks!
