### ISSUE TITLE
Generated Token not accepted through Swift SDK?

### ISSUE THREAD

**Issue by we5** [GetStream/stream-chat-ruby#4]
Hi there,

we recently tried to switch from development tokens to actual real tokens for final testing and found out, that the token I generate through this method:
https://github.com/GetStream/stream-chat-ruby/blob/e57f7dc21371a397a4a9742e53f97e13946b3407/lib/stream-chat/client.rb#L40-L46

Unfortunately if we use this token via the Swift SDK the requests will be rejected with a 401 and the message that the signature of this token is not valid. Validating this ourselves by using https://jwt.io/#debugger-io is looking good.

Maybe we are doing something wrong but as I am only forwarding the generated token to the client, and the token is not even set-up to expire in the future, we are kind of clueless now.

**Comment by tbarbugli** [comment]
Are you using the same api key in ruby and on swift?

**Comment by we5** [comment]
hi @tbarbugli 

I just checked with the iOS developer and indeed we are using different ones. We checked on another environment and it worked but I found out that this was configured to use the earlier one.

Sorry for bothering.
