### ISSUE TITLE
Creating channel without ID for Team

### ISSUE THREAD

**Issue by kcollignon** [GetStream/stream-chat-ruby#50]
Hello,

When creating channels with a multi-tenant `team` parameter, I noticed that the `team` attribute doesn't seem to save the associated if the Channel ID given is empty?

Works:

```ruby
chan = @client.channel('messaging', channel_id: 'kevin-nikki', data: {'members'=> ['123', '456'], 'team' => '789'})
```

Does Not Work:

```ruby
chan = @client.channel('messaging', channel_id: nil, data: {'members'=> ['123','456'], 'team' => '789'})
```

**Comment by ffenix113** [comment]
With current version I can't reproduce this. Please reopen this issue if you still have any issues with it.

Thank you for the report.
