### ISSUE TITLE
Get unread messages from an user in a channel

### ISSUE THREAD

**Issue by kidush** [GetStream/stream-chat-ruby#57]
Hi guys, 

I don't know if here is the best place to get some help with that, but I couldn't find anywhere something related to that. Is there a way to get the unread_messages from one specific user in a channel?

**Comment by peterdeme** [comment]
Hello! [Query Channel API](https://getstream.io/chat/docs/other-rest/query_channels/) returns the unread count. A while ago I made a [quick Python snippet](https://pastebin.com/KedEWajH) to showcase it. The same applies to Ruby.

Thanks!
