### ISSUE TITLE
Use development dependencies

### ISSUE THREAD

**Issue by ghiculescu** [GetStream/stream-chat-ruby#8]
Would it be possible to mark gems like `rspec`, `simplecov` etc as dev depenencies in https://github.com/GetStream/stream-chat-ruby/blob/master/stream-chat.gemspec#L18..L22

Currently adding this gem to a project causes it to add a bunch of extra gems that I presume aren't needed at runtime.

**Comment by tbarbugli** [comment]
@ghiculescu good point! feel free to contribute a PR; if you don't have time for it we'll get around this later this week

**Comment by Bogdan-D** [comment]
@ghiculescu thank you for PR :)
