### ISSUE TITLE
JWT format error on create_token method

### ISSUE THREAD

**Issue by codingwaysarg** [GetStream/stream-chat-ruby#96]
Hi there,

I was comparing the JWT token generated by the **create_token** method, and it doesn't match with the one generated by this test site: https://getstream.io/chat/docs/javascript/token_generator/

if you decode both tokens using https://jwt.io/, there is a small difference on the decoded value.
The header from the getstream.io token has "typ": "JWT", while the generated on this library doesn't.

This difference makes the token different and it fails when you try to use it on the frontend.
I've tried generating the token using this code, by adding the typ: 'JWT' and now it works:

```
JWT.encode(
      {
        user_id: 'my-user-id'
      },
      @client.api_secret,
      'HS256',
      {
        typ: 'JWT'
      }
    )
```

**Comment by ferhatelmas** [comment]
that header parameter is optional: https://datatracker.ietf.org/doc/html/rfc7519#section-5.1

That's why it can't be the cause of the problem. What is the error you're getting or could you share the code snippet how you called the SDK (and version of SDK and gem)?

cc @peterdeme

**Comment by codingwaysarg** [comment]
React: "stream-chat": "^6.5.0"
Ruby: stream-chat-ruby (2.22.0)

If if use create_token I'm getting this error: "Error: userToken does not have a user_id or is not matching with user.id"
Code:

```
@client = StreamChat::Client.from_env
@client.create_token('my-user-id')
```

Then on the client side:

```
const chatClient = StreamChat.getInstance(process.env.REACT_APP_STREAM_KEY);
chatClient.connectUser(
    {
      'my-user-id',
      name: 'Name'
    },
    'token generated by ruby'
  );

```

**Comment by ferhatelmas** [comment]
This error isn't coming from backend. It's a user token validation in JS SDK and it doesn't use the JWT header (only payload)

so my guess is that 
1. there is a race and token isn't passed correctly to `connectUser` call
2. there is a logical mistake and id used in your backend and client don't really match

Logging around `connectUser` should help to find out the problem.

**Comment by codingwaysarg** [comment]
The weird thing is that if I add that header, it works..
I've already tried logging my id and token, and everything is ok..

I'm gonna keep trying a few times and let you guys know.
Thank you.
